plugins:
  - remark-mdx
  - remark-frontmatter
  - remark-gfm
  - remark-deflist
  - remark-preset-lint-recommended
  - remark-preset-lint-markdown-style-guide
  - - remark-lint-no-file-name-irregular-characters
    - "\\.a-zA-Z0-9_-"
